### ISSUE TITLE
Flipped tiles not flipped after exporting

### ISSUE THREAD

**Issue by D00Med** [MikeMnD/tiled-to-godot-export#12]
Hello, thankyou so much for creating this plugin. 
I tried to export a tilemap with flipped tiles (in Tiled), but they are not flipped when I open the map in Godot 3.2.
Just to check, I tried adding flipped tiles using godot, and it works correctly using an exported tilemap.

**Comment by bjorn** [comment]
It appears @MikeMnD is short on time at the moment since he wasn't active on GitHub for the last two months. Would you be interested in looking into adding support for flipped tiles to this script? I can help if you have any questions.

**Comment by D00Med** [comment]
I don't think I would know the first thing about doing that. But I'll have a glance, will reply if I think I can do something.

**Comment by MikeMnD** [comment]
Hello there :)
So I've started adding the tile flip and rotate but it's still only on my locale machine and sits there.
I'll try to wrap it up and update the export script since this wasn't super hard but wasn't trivial cause Godot has some strange encodings for coordinates and rotations...

**Comment by MikeMnD** [comment]
Ok, It took me some time to solve the puzzle but it seems to work pretty fine.
I've released the 1.3 version which includes the margin fix and the rotation and flipping.

https://github.com/MikeMnD/tiled-to-godot-export/releases/tag/1.3

Cheers.

**Comment by D00Med** [comment]
Ah thankyou very much! Your work has saved me a lot of trouble.
