### ISSUE TITLE
Exporting undefined property

### ISSUE THREAD

**Issue by alextrevisan** [MikeMnD/tiled-to-godot-export#3]
Hi, first of all, thanks for the exporter!

But there is a problem when exporting tilesets. The final file (line 10) is like this:

`0/region = Rect2( 0, 0, undefined, undefined )`

and I believe is this line but I dont know how to fix:

`0/region = Rect2( 0, 0, ${this.tileset.imageWidth}, ${this.tileset.imageHeight} )`

Thanks

EDIT: Works on Snapshot Windows version: Version 2020.04.10

**Comment by bjorn** [comment]
Maybe read the `README.md`, it's the first thing mentioned. ;-)

Anyway, I think I'll soon release Tiled 1.3.4 and will consider to cherry-pick these additions from the `master` branch. Though in any case Tiled 1.4 should only take a few more weeks now.

**Comment by alextrevisan** [comment]
Ouch, after this I found, sorry.
I'm working on multiple tilesets in the same layer. Already working if you are interested let me know. Thanks.
