### ISSUE TITLE
Tilemap flags - Filter

### ISSUE THREAD

**Issue by PseudoFanboy** [MikeMnD/tiled-to-godot-export#34]
Hi,
I'm importing maps and sets successfully to Godot 3.3.2, but regardless of Import Settings ("Tileset from Tiled") on the tileset resource (.tsx) my pixel tiles blur as if the Filter flag were on (whether or not it is). I've tried the preset "Pixel Art" but there is no change.
Is this a matter of the tool not being updated yet for 3.3, or have I missed a step in the process?

**Comment by mcarpenter622** [comment]
It sounds like you are mixing tools? You should be using this exporter or the Godot Importer, not both. This one exports tiled files .tms and .tsx to .tscn and .tres.  You should only need to pull in the tscn and tres files that this tool exports into Godot.

**Comment by mcarpenter622** [comment]
I set this import defaults when pulling in images for my 2D project in Godot and it fixed any blurriness I had.

![image](https://user-images.githubusercontent.com/13891542/157344158-264af518-24f1-4551-816d-0234b58ceb7e.png)

**Comment by PseudoFanboy** [comment]
YEP I sure was using both, got very mixed up. Thank you very much for the help!
